name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Runs the action on pushes to the "main" branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js in frontend directory
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify Node.js version
          cache: 'npm' # Cache npm dependencies
          cache-dependency-path: frontend/package-lock.json # Specify the lock file location

      # Step 3: Install dependencies
      - name: Install dependencies
        working-directory: frontend
        run: npm install

      # Step 4: Build the project
      - name: Build project
        working-directory: frontend
        run: npm run build

      # Step 5: Upload the build artifacts for GitHub Pages
      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v2
        with:
          path: frontend/build # The directory of your built static files

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write  # Grants access to deploy to GitHub Pages
      id-token: write # Necessary for deployment authentication

    steps:
      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
